In [1]:
import numpy as np

In [6]:
 a = np.random.randint(100, size=(3,3))

In [7]:
a

array([[83, 49, 75],
       [35, 87,  4],
       [97, 99, 71]])

In [8]:
a>=60

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [9]:
a[a>=40]

array([83, 49, 75, 87, 97, 99, 71])

In [10]:
a.mean()

66.66666666666667

In [15]:
a[~(a>a.mean())]

array([49, 35,  4])